on: push
name: Build and deploy blog pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build blog pages
        uses: shalzz/zola-deploy-action@v0.14.1
        env:
          BUILD_ONLY: true
      - name: Deploy blog
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_TARGET: ${{ secrets.REMOTE_TARGET }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          rsync --rsh "ssh -i ~/.ssh/deploy_key" --exclude='/.*' -zrlt --delete artifacts/ $REMOTE_USER@$REMOTE_HOST:$REMOTE_TARGET

