on: push
name: Build and deploy blog pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build blog pages
        uses: leo1003/zola-build@v0.0.3
      - name: Deploy blog
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_TARGET: ${{ secrets.REMOTE_TARGET }}
          REMOTE_HOST_KEY: ${{ secrets.REMOTE_HOST_KEY }}
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$REMOTE_HOST $REMOTE_HOST_KEY" >> ~/.ssh/known_hosts
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          rsync --rsh "ssh -i ~/.ssh/deploy_key" --exclude='/.*' -zrlt --delete artifacts/ $REMOTE_USER@$REMOTE_HOST:$REMOTE_TARGET
      - name: Cleanup
        if: always()
        run: |
          rm -f ~/.ssh/deploy_key

